import { z } from "zod";
import type { AppState, CurriculumContext } from "@/domain/types";

export const LessonReadinessSchema = z.object({ learningIntention: z.string(), priorLearning: z.string(), segments: z.array(z.object({ title: z.string(), durationMinutes: z.number(), activity: z.string(), rationale: z.string(), sourceCategory: z.enum(["CURRICULUM", "ATE"]) })), formativeCheck: z.object({ method: z.string(), evidenceExpected: z.string() }), resourceNeeds: z.array(z.string()), teacherWatchouts: z.array(z.string()) });
export type LessonReadinessOutput = z.infer<typeof LessonReadinessSchema>;
export type LessonReadinessRequest = { state: AppState; sectionId: string; curriculumContext: CurriculumContext; prompt?: string };
export const AssessmentDraftSchema = z.object({ title: z.string(), instructions: z.array(z.string()), questions: z.array(z.object({ text: z.string(), marks: z.number(), questionType: z.string(), difficulty: z.enum(["LOW", "MEDIUM", "HIGH"]), learningOutcomeIds: z.array(z.string()), markingGuide: z.array(z.object({ point: z.string(), marks: z.number() })) })) });
export type AssessmentDraftOutput = z.infer<typeof AssessmentDraftSchema>;
export type AssessmentDraftRequest = { mode: string; allowedLearningOutcomeIds: string[]; topicTitle: string; totalMarks: number; curriculumContext?: CurriculumContext };
export interface AssessmentProvider { generateAssessment(request: AssessmentDraftRequest): Promise<AssessmentDraftOutput> }
export interface AIProvider { generateLessonReadiness(request: LessonReadinessRequest): Promise<LessonReadinessOutput> }
export const AskATEResponseSchema = z.object({ answer: z.string(), suggestedFollowUps: z.array(z.string()).max(3) });
export type AskATEResponse = z.infer<typeof AskATEResponseSchema>;
export type AskATERequest = { question: string; role: "TEACHER" | "HOD" | "DOS" | "PRINCIPAL"; curriculumContext?: CurriculumContext; sectionId?: string };
export interface AskATEProvider { ask(request: AskATERequest): Promise<AskATEResponse> }
export const fixtureAskATEProvider: AskATEProvider = { async ask(request) { return AskATEResponseSchema.parse({ answer: `ATE could not reach the live provider. Your question remains advisory and no academic state was changed: ${request.question}`, suggestedFollowUps: ["Review the current curriculum context", "Check the Teaching Section state"] }); } };
export const fixtureAIProvider: AIProvider = { async generateLessonReadiness(request) { const { curriculumContext } = request; const section = request.state.sections.find((item) => item.id === request.sectionId); const outcome = curriculumContext.topic.learningOutcomes.find((item) => item.review.state === "VERIFIED"); const activity = curriculumContext.topic.suggestedLearningActivities[0]; return LessonReadinessSchema.parse({ learningIntention: outcome ? `Learners will ${outcome.text}.` : `Learners will explore ${curriculumContext.topic.title}.`, priorLearning: curriculumContext.currentOutcomeStatus === "UNCONFIRMED" ? "No previous outcome has been confirmed for this Teaching Section." : "Reconnect with the last teacher-confirmed outcome before extending the work.", segments: [{ title: "Connect", durationMinutes: 10, activity: "Use a short retrieval prompt to surface prior understanding.", rationale: "Builds from the confirmed class position.", sourceCategory: "ATE" }, { title: "Investigate", durationMinutes: 30, activity: activity?.text ?? "Use the configured curriculum activity to investigate the topic.", rationale: "Uses a suggested activity from the canonical curriculum context.", sourceCategory: "CURRICULUM" }, { title: "Check", durationMinutes: 10, activity: "Learners explain one observation and respond to a hinge question.", rationale: "Provides immediate formative evidence.", sourceCategory: "ATE" }], formativeCheck: { method: curriculumContext.topic.sampleAssessmentStrategies[0]?.text ?? "One-minute explanation", evidenceExpected: outcome?.text ?? "Evidence of understanding using the lesson vocabulary." }, resourceNeeds: ["Board and learner notebooks", ...(section?.constraints ?? [])], teacherWatchouts: [...curriculumContext.topic.review.reasons, "Do not treat an unconfirmed prior lesson as missed."] }); } };
export const fixtureAssessmentProvider: AssessmentProvider = { async generateAssessment(request) { const outcomes = request.curriculumContext?.topic.learningOutcomes ?? []; return AssessmentDraftSchema.parse({ title: `${request.topicTitle} · ${request.mode.replaceAll("_", " ")}`, instructions: ["Answer all questions.", "Use clear biological vocabulary."], questions: request.allowedLearningOutcomeIds.slice(0, 3).map((id, index) => { const outcome = outcomes.find((item) => item.id === id); return { text: outcome ? `Explain: ${outcome.text}` : `Explain one important idea connected to ${request.topicTitle}.`, marks: index === 0 ? 4 : 3, questionType: "Short answer", difficulty: index === 0 ? "MEDIUM" : "LOW", learningOutcomeIds: [id], markingGuide: [{ point: "Accurate biological idea", marks: 2 }, { point: "Relevant example or explanation", marks: index === 0 ? 2 : 1 }] }; }) }); } };
