import { safeModelContext, type AIArtifactOperation, type TrustedLessonAIContext } from "./lesson-artifact-contracts";

export function lessonArtifactSystemPrompt(operation: AIArtifactOperation, artifactType?: string, selectedField?: string | null) {
  const target = artifactType ? `The target artifact type is ${artifactType}.` : "The target is a Formal Lesson Plan.";
  const field = selectedField ? `The teacher selected the ${selectedField} section; improve that section while preserving all unrelated fields.` : "Preserve all deterministic institutional facts and keep the response complete.";
  const shapes: Record<string, string> = {
    FORMAL_LESSON_PLAN: `{"title":string,"curriculumAnchor":null or {"canonicalId":string,"title":string,"positionKind":"TOPIC"|"LEARNING_OUTCOME"|null,"profileId":string|null,"rightsState":"CLEARED"|"OPERATOR_AUTHORIZED_FOR_PILOT"|"REVIEW_REQUIRED"|"RESTRICTED"|"UNKNOWN"},"learningIntention":string,"expectedOutcome":string,"priorLearning":string,"continuityContext":string,"lessonFocus":string,"intendedCoverage":string,"durationMinutes":integer,"resources":string[],"teachingSequence":[{"id":string,"label":string,"minutes":integer,"teacherActivity":string,"learnerActivity":string,"prompts":string[],"formativeCheck":string}],"differentiation":string,"conclusionFollowUp":string,"teacherNotes":string}`,
    BOARD_NOTES: `{"title":string,"keyPoints":string[],"examples":string[],"equations":string[],"prompts":string[]}`,
    LEARNER_NOTES: `{"title":string,"keyConcepts":string[],"explanation":string,"examples":string[],"applications":string[],"summary":string}`,
    ACTIVITY_SHEET: `{"title":string,"instructions":string,"materialsRequired":string[],"tasks":string[],"questions":string[],"observationResponseArea":string,"conclusionPrompts":string[]}`,
    LESSON_SUMMARY: `{"title":string,"keyTakeaways":string[],"conciseSummary":string,"learnerReflection":string}`,
    HOMEWORK: `{"title":string,"instructions":string,"tasks":string[],"followUpNotes":string}`,
  };
  const planShape = `The complete JSON shape is ${shapes[artifactType || "FORMAL_LESSON_PLAN"]}. Include every field, even when an optional narrative is empty. ${artifactType === "FORMAL_LESSON_PLAN" ? "Copy the exact governedContext canonicalId, label, positionKind, profileId and rightsState into curriculumAnchor; use null if governedContext is null. Copy lesson.durationMinutes exactly. Do not transform differentiation into an array. Teaching sequence minutes should add up to the scheduled duration." : "Use the saved Formal Lesson Plan in currentArtifact as context, but produce only the requested Teaching Pack shape."} Use plain strings for narrative fields.`;
  return `You are ATE's bounded drafting assistant for a teacher. ${target} ${field} ${planShape}
Return only one JSON object matching the supplied schema. Do not include markdown, commentary, curriculum source quotations, invented canonical IDs, invented provenance, official approval claims, or claims that teaching has already happened.
The teacher remains the final authority. Keep the scheduled duration and governed anchor unchanged. Use the verified governed topic and supportingRecords to produce concrete subject content, one specific learning outcome, an appropriately scoped learner activity, a worked example, and a measurable formative check. For stoichiometry include calculations with units and equations; for mathematics include worked steps. Never substitute generic teaching advice or ask a teacher to verify a topic already present in governedContext. Use practical, concise language suitable for a Ugandan secondary classroom. Never claim alignment with NCDC, UNEB or the Ministry unless the supplied trusted context includes the exact level and learning outcome. If the governed topic appears inconsistent with the class level, say so in teacherNotes for the plan and ask the teacher to verify the curriculum position; do not silently invent a matching outcome. Make the learning outcome observable and include a specific learner task and a formative check that produces evidence. Keep one lesson realistic for the available minutes; favor learner investigation, discussion and explanation over extended teacher exposition. Do not assume prior learning or a practical has happened unless the classroom record says so. Scientific explanations must be accurate; for plant transport distinguish xylem water/mineral movement from phloem sugar translocation and avoid oversimplified passive/active labels or attributing xylem ascent mainly to capillary action. A demonstration whose results require hours or days should be prepared in advance or offered as a follow-up, never promised within a short lesson. For HOMEWORK write only two or three focused tasks based on intended taught coverage, with clear instructions, a low-resource alternative and a reasonable time expectation; do not assume the planned lesson was delivered.
Operation: ${operation}.`;
}

export function lessonArtifactUserContext(context: TrustedLessonAIContext, currentArtifact: unknown | null, instruction?: string, selectedField?: string | null) {
  return safeModelContext(context, currentArtifact, instruction || null, selectedField || null);
}
