import { bigint, date, index, integer, jsonb, pgTable, text, timestamp, uuid, unique } from "drizzle-orm/pg-core";

export const schools = pgTable("schools", { id: uuid("id").defaultRandom().primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), status: text("status").notNull(), timezone: text("timezone").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() }, (table) => [unique("schools_slug_unique").on(table.slug)]);
export const memberships = pgTable("memberships", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), userId: uuid("user_id").notNull(), status: text("status").notNull(), displayName: text("display_name").notNull(), joinedAt: timestamp("joined_at", { withTimezone: true }), deactivatedAt: timestamp("deactivated_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [unique("memberships_school_user_unique").on(table.schoolId, table.userId), index("memberships_user_status_idx").on(table.userId, table.status)]);
export const departments = pgTable("departments", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), name: text("name").notNull(), code: text("code").notNull(), status: text("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() }, (table) => [unique("departments_school_code_unique").on(table.schoolId, table.code)]);
export const roleGrants = pgTable("role_grants", { id: uuid("id").defaultRandom().primaryKey(), membershipId: uuid("membership_id").notNull(), schoolId: uuid("school_id").notNull(), role: text("role").notNull(), scopeType: text("scope_type").notNull(), departmentId: uuid("department_id"), status: text("status").notNull(), grantedBy: uuid("granted_by"), grantedAt: timestamp("granted_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }) }, (table) => [index("role_grants_school_role_status_idx").on(table.schoolId, table.role, table.status)]);
export const academicPeriods = pgTable("academic_periods", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), name: text("name").notNull(), periodType: text("period_type").notNull(), academicYear: integer("academic_year").notNull(), startsOn: date("starts_on").notNull(), endsOn: date("ends_on").notNull(), status: text("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() }, (table) => [index("academic_periods_school_dates_idx").on(table.schoolId, table.startsOn, table.endsOn)]);
export const invitations = pgTable("invitations", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), emailNormalized: text("email_normalized").notNull(), tokenHash: text("token_hash").notNull(), status: text("status").notNull(), intendedRole: text("intended_role"), departmentId: uuid("department_id"), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), acceptedBy: uuid("accepted_by"), acceptedAt: timestamp("accepted_at", { withTimezone: true }), createdBy: uuid("created_by").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [unique("invitations_token_hash_unique").on(table.tokenHash), index("invitations_school_status_expiry_idx").on(table.schoolId, table.status, table.expiresAt)]);
export const auditEvents = pgTable("audit_events", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), actorUserId: uuid("actor_user_id"), action: text("action").notNull(), resourceType: text("resource_type").notNull(), resourceId: uuid("resource_id"), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), requestId: text("request_id"), metadata: jsonb("metadata").notNull(), beforeState: jsonb("before_state"), afterState: jsonb("after_state") }, (table) => [index("audit_events_school_time_idx").on(table.schoolId, table.occurredAt)]);
export const schoolFiles = pgTable("school_files", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), bucketId: text("bucket_id").notNull(), objectPath: text("object_path").notNull(), fileKind: text("file_kind").notNull(), classification: text("classification").notNull(), mimeType: text("mime_type").notNull(), sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(), checksumSha256: text("checksum_sha256"), uploadedBy: uuid("uploaded_by").notNull(), status: text("status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [unique("school_files_bucket_path_unique").on(table.bucketId, table.objectPath), index("school_files_school_classification_idx").on(table.schoolId, table.classification, table.status)]);
