import { date, integer, jsonb, pgTable, text, timestamp, uuid, unique, index } from "drizzle-orm/pg-core";
import { academicPeriods, memberships, schools } from "@/security/db/schema";
import { knowledgeAssessmentProfiles, knowledgeRecords, knowledgeSubjectProfiles } from "@/knowledge/db/schema";

export const assessmentWorkspaces = pgTable("assessment_workspaces", {
  id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id),
  academicPeriodId: uuid("academic_period_id").notNull().references(() => academicPeriods.id), schoolSubjectId: uuid("school_subject_id").notNull(),
  curriculumSubjectProfileId: uuid("curriculum_subject_profile_id").notNull().references(() => knowledgeSubjectProfiles.id), assessmentProfileId: uuid("assessment_profile_id").notNull().references(() => knowledgeAssessmentProfiles.id),
  purpose: text("purpose").notNull(), title: text("title").notNull(), status: text("status").notNull(), durationMinutes: integer("duration_minutes").notNull(), totalMarks: integer("total_marks").notNull(), assessmentDate: date("assessment_date").notNull(), currentVersionId: uuid("current_version_id"), finalisedByMembershipId: uuid("finalised_by_membership_id"), finalisedAt: timestamp("finalised_at", { withTimezone: true }), profileSnapshot: jsonb("profile_snapshot").notNull(), scopeSnapshot: jsonb("scope_snapshot"), createdByMembershipId: uuid("created_by_membership_id").notNull().references(() => memberships.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
}, (table) => [index("assessment_workspaces_teacher_idx").on(table.schoolId, table.createdByMembershipId, table.updatedAt)]);

export const assessmentWorkspaceSections = pgTable("assessment_workspace_sections", { assessmentWorkspaceId: uuid("assessment_workspace_id").notNull(), schoolId: uuid("school_id").notNull(), teachingSectionId: uuid("teaching_section_id").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [unique("assessment_workspace_sections_unique").on(table.assessmentWorkspaceId, table.teachingSectionId)]);
export const assessmentScopeItems = pgTable("assessment_scope_items", { id: uuid("id").defaultRandom().primaryKey(), assessmentWorkspaceId: uuid("assessment_workspace_id").notNull(), schoolId: uuid("school_id").notNull(), canonicalId: text("canonical_id").notNull().references(() => knowledgeRecords.canonicalId), scopeState: text("scope_state").notNull(), evidenceType: text("evidence_type").notNull(), evidenceReferenceId: text("evidence_reference_id"), classroomEvidenceId: uuid("classroom_evidence_id"), curriculumPositionEventId: uuid("curriculum_position_event_id"), sectionId: uuid("section_id"), overrideReason: text("override_reason"), confirmedByMembershipId: uuid("confirmed_by_membership_id"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [index("assessment_scope_items_lookup_idx").on(table.schoolId, table.assessmentWorkspaceId, table.scopeState, table.canonicalId)]);
export const assessmentVersions = pgTable("assessment_versions", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), assessmentWorkspaceId: uuid("assessment_workspace_id").notNull(), versionNumber: integer("version_number").notNull(), contentJson: jsonb("content_json").$type<Record<string, unknown>>().notNull(), changeSource: text("change_source").notNull(), changeSummary: text("change_summary"), createdByMembershipId: uuid("created_by_membership_id").notNull().references(() => memberships.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [unique("assessment_versions_workspace_number_unique").on(table.assessmentWorkspaceId, table.versionNumber), index("assessment_versions_lookup_idx").on(table.schoolId, table.assessmentWorkspaceId, table.versionNumber)]);
export const assessmentAiGenerationRuns = pgTable("assessment_ai_generation_runs", { id: uuid("id").defaultRandom().primaryKey(), schoolId: uuid("school_id").notNull().references(() => schools.id), assessmentWorkspaceId: uuid("assessment_workspace_id").notNull(), createdByUserId: uuid("created_by_user_id").notNull(), createdByMembershipId: uuid("created_by_membership_id").notNull(), provider: text("provider").notNull(), model: text("model").notNull(), promptVersion: text("prompt_version").notNull(), contextFingerprint: text("context_fingerprint").notNull(), contextSnapshot: jsonb("context_snapshot").notNull(), outputFingerprint: text("output_fingerprint"), outputJson: jsonb("output_json"), status: text("status").notNull(), validationStatus: text("validation_status").notNull(), rightsState: text("rights_state").notNull(), inputTokenCount: integer("input_token_count"), outputTokenCount: integer("output_token_count"), latencyMs: integer("latency_ms"), errorCode: text("error_code"), createdAt: timestamp("created_at", { withTimezone: true }).notNull() }, (table) => [index("assessment_ai_runs_lookup_idx").on(table.schoolId, table.assessmentWorkspaceId, table.createdAt)]);
