"use client";

import { ArrowLeft, ArrowDown, ArrowUp, Check, ClipboardCheck, LockKeyhole, Plus, Save, Sparkles, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { useMemo, useState } from "react";
import { AssessmentPayloadSchema, assessmentDifficulties, assessmentItemTypes, type AssessmentPayload } from "@/assessment/domain/types";
import { confirmPartialAssessmentScope, finalizeAssessment, saveAssessmentVersion, submitAssessmentForReview } from "@/assessment/application/actions";
import { acceptAssessmentDraft, generateAssessmentDraft, rejectAssessmentDraft, type AssessmentProposal } from "@/assessment/application/ai-actions";
import type { AssessmentWorkspaceData } from "@/assessment/application/queries";
import { canTeacherEditAssessment } from "@/leadership/domain/assessment-review";

function clone<T>(value: T): T { return structuredClone(value); }
function text(value: unknown) { return typeof value === "string" ? value : ""; }

export function AssessmentWorkspace({ data }: { data: AssessmentWorkspaceData }) {
  const router = useRouter();
  const [payload, setPayload] = useState<AssessmentPayload>(clone(data.version.content_json));
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [proposal, setProposal] = useState<Extract<AssessmentProposal, { ok: true }> | null>(null);
  const [aiBusy, setAiBusy] = useState(false);
  const [partialSelections, setPartialSelections] = useState<string[]>([]);
  const final = text(data.workspace.status) === "FINAL";
  const inReview = text(data.workspace.status) === "IN_REVIEW";
  const requiresReview = data.runtimeProfile?.requiresReview === true;
  const teacherLocked = !canTeacherEditAssessment(inReview ? "IN_REVIEW" : final ? "FINAL" : "DRAFT");
  const questionMarks = payload.questions.reduce((sum, question) => sum + question.marks, 0);
  const eligibleCanonicalIds = useMemo(() => {
    const canonicalIds = [...new Set(data.scopeItems.map((item) => text(item.canonical_id)))];
    if (text(data.workspace.purpose) !== "COMMON_STREAM_TEST") return new Set(canonicalIds.filter((id) => data.scopeItems.some((item) => text(item.canonical_id) === id && ["CONFIRMED_ELIGIBLE", "BROADER_PROFILE_PERMITTED"].includes(text(item.scope_state)))));
    return new Set(canonicalIds.filter((id) => data.sections.every((section) => data.scopeItems.some((item) => text(item.canonical_id) === id && text(item.section_id) === text(section.teaching_section_id) && ["CONFIRMED_ELIGIBLE", "BROADER_PROFILE_PERMITTED"].includes(text(item.scope_state))))));
  }, [data.scopeItems, data.sections, data.workspace.purpose]);
  const outOfScope = payload.questions.filter((question) => question.canonicalIds.some((id) => !eligibleCanonicalIds.has(id))).length;
  const errors = useMemo(() => { const parsed = AssessmentPayloadSchema.safeParse(payload); return parsed.success ? [] : parsed.error.issues.map((issue) => issue.message); }, [payload]);
  const partialCandidates = data.partialScopeCandidates.filter((candidate) => !data.scopeItems.some((item) => text(item.section_id) === candidate.sectionId && text(item.canonical_id) === candidate.canonicalId && text(item.evidence_type) === "EXPLICIT_PARTIAL_SCOPE_CONFIRMATION"));
  function updateQuestion(index: number, patch: Partial<AssessmentPayload["questions"][number]>) { setPayload((current) => { const next = clone(current); next.questions[index] = { ...next.questions[index], ...patch }; return next; }); }
  function move(index: number, direction: -1 | 1) { setPayload((current) => { const next = clone(current); const target = index + direction; if (target < 0 || target >= next.questions.length) return next; [next.questions[index], next.questions[target]] = [next.questions[target], next.questions[index]]; return next; }); }
  function addQuestion() { setPayload((current) => ({ ...current, questions: [...current.questions, { id: `q-${Date.now()}`, text: "", marks: 1, itemType: "SHORT_ANSWER", difficulty: "MEDIUM", cognitiveDemand: null, canonicalIds: current.blueprint.scopeCanonicalIds.slice(0, 1), markingGuide: [""], expectedResponse: null, rubric: null }] })); }
  async function save() { setMessage(""); const parsed = AssessmentPayloadSchema.safeParse(payload); if (!parsed.success) { setMessage(parsed.error.issues[0]?.message || "Complete the assessment fields before saving."); return; } setBusy(true); const result = await saveAssessmentVersion(text(data.workspace.id), payload, Number(data.version.version_number)); setBusy(false); setMessage(result.ok ? "Saved as a new teacher version." : result.error || "Assessment could not be saved."); if (result.ok) router.refresh(); }
  async function finalize() { setMessage(""); if (questionMarks !== Number(data.workspace.total_marks)) { setMessage(`Question marks total ${questionMarks}; the blueprint requires ${text(data.workspace.total_marks)}.`); return; } if (outOfScope) { setMessage("Remove questions outside the confirmed eligible scope before finalising."); return; } setBusy(true); const result = await finalizeAssessment(text(data.workspace.id), Number(data.version.version_number)); setBusy(false); setMessage(result.ok ? "Assessment finalised. The current version is now immutable." : result.error || "Assessment could not be finalised."); if (result.ok) router.refresh(); }
  async function submitForReview() { setMessage(""); if (questionMarks !== Number(data.workspace.total_marks)) { setMessage(`Question marks total ${questionMarks}; the blueprint requires ${text(data.workspace.total_marks)}.`); return; } if (outOfScope) { setMessage("Remove questions outside the confirmed eligible scope before submitting for review."); return; } setBusy(true); const result = await submitAssessmentForReview(text(data.workspace.id), Number(data.version.version_number)); setBusy(false); setMessage(result.ok ? "Assessment submitted for academic review. Editing is now frozen." : result.error || "Assessment could not be submitted for review."); if (result.ok) router.refresh(); }
  async function generateAI() { setMessage(""); setAiBusy(true); const result = await generateAssessmentDraft(text(data.workspace.id)); setAiBusy(false); if (!result.ok) { setMessage(result.error); return; } setProposal(result); }
  async function acceptAI() { if (!proposal) return; setAiBusy(true); const result = await acceptAssessmentDraft(text(data.workspace.id), proposal.runId, proposal.outputFingerprint, proposal.expectedVersion); setAiBusy(false); setMessage(result.ok ? "ATE proposal accepted as a new AI-authored version. Review it before saving or finalising." : result.error || "AI proposal could not be accepted."); if (result.ok) { setProposal(null); router.refresh(); } }
  async function rejectAI() { if (!proposal) return; setAiBusy(true); const result = await rejectAssessmentDraft(proposal.runId); setAiBusy(false); setMessage(result.ok ? "ATE proposal rejected; no assessment version was created." : result.error || "AI proposal could not be rejected."); if (result.ok) setProposal(null); }
  async function confirmPartialScope() {
    const selected = partialCandidates.filter((candidate) => partialSelections.includes(`${candidate.sectionId}:${candidate.canonicalId}`));
    if (!selected.length) { setMessage("Select the partially covered portion that is ready for assessment."); return; }
    setBusy(true);
    const results = await Promise.all(selected.map((candidate) => confirmPartialAssessmentScope(text(data.workspace.id), candidate.sectionId, candidate.canonicalId, candidate.evidenceReferenceId)));
    setBusy(false);
    const failure = results.find((result) => !result.ok);
    setMessage(failure?.error || "The selected partial scope is now explicitly eligible for assessment.");
    if (!failure) { setPartialSelections([]); router.refresh(); }
  }
  return <main className="assessment-page">
    <div className="assessment-back-row"><Link className="back-link" href="/workspace/teacher/assessments"><ArrowLeft size={14} />Assessment Studio</Link><span className={`assessment-status ${final ? "final" : inReview ? "review" : "draft"}`}>{final ? <LockKeyhole size={13} /> : <ClipboardCheck size={13} />}{text(data.workspace.status)} · v{data.version.version_number}</span></div>
    <header className="assessment-heading workspace-heading"><div><p className="eyebrow">{text(data.workspace.purpose).replaceAll("_", " ")}</p><h1>{text(data.workspace.title)}</h1><p className="lede">Purpose, profile, eligible scope, blueprint and teacher-authored questions stay visible in one working surface.</p></div><div className="assessment-heading-note"><Check size={16} /><span>Current version<br /><small>{text(data.version.change_source)} authored</small></span></div></header>
    <section className="assessment-stage-strip" aria-label="Assessment workflow"><span className="complete">1 Purpose</span><span className="complete">2 Profile</span><span className="complete">3 Eligible scope</span><span className="complete">4 Blueprint</span><span className="active">5 Draft & review</span><span>6 Finalise / export</span></section>
    <section className="assessment-context-grid"><div className="assessment-context-panel"><span className="section-kicker">Applicable profile</span><h2>{data.runtimeProfile?.displayTitle || "Profile unavailable"}</h2><p>{data.profileResolution.explanation}</p><div className="profile-facts"><span>Profile status<strong>{data.profileResolution.state}</strong></span><span>Source readiness<strong>{data.runtimeProfile?.rightsState === "CLEARED" ? "READY" : "REVIEW"}</strong></span><span>Export<strong>{data.runtimeProfile?.exportAllowed ? "Available" : "Unavailable"}</strong></span></div></div><div className="assessment-context-panel scope-panel"><span className="section-kicker">Eligible scope</span><h2>{eligibleCanonicalIds.size} outcomes available</h2><p>Confirmed taught content is distinct from profile-defined broader scope. No mastery is inferred.</p><div className="scope-tags">{data.scopeItems.slice(0, 12).map((item) => <span className={text(item.scope_state) === "BROADER_PROFILE_PERMITTED" ? "broader" : "confirmed"} key={text(item.id)}>{text(item.canonical_id)}</span>)}</div></div></section>
    {partialCandidates.length > 0 && <section className="assessment-partial-scope" aria-labelledby="partial-scope-heading"><div><span className="section-kicker">Classroom continuity</span><h2 id="partial-scope-heading">Partially covered content</h2><p>The latest classroom evidence is partial. Explicitly confirm the portion that is ready for assessment; ATE will not make all partial content eligible automatically.</p></div><div className="partial-scope-options">{partialCandidates.map((candidate) => { const key = `${candidate.sectionId}:${candidate.canonicalId}`; return <label className="partial-scope-option" key={key}><input type="checkbox" checked={partialSelections.includes(key)} onChange={(event) => setPartialSelections((current) => event.target.checked ? [...current, key] : current.filter((item) => item !== key))} disabled={teacherLocked || busy} /><span><strong>{candidate.canonicalId}</strong><small>Teaching Section {candidate.sectionId} · current partial classroom evidence</small></span></label>; })}</div><button className="button button-primary" onClick={confirmPartialScope} disabled={teacherLocked || busy || partialSelections.length === 0}><Check size={15} />{busy ? "Confirming…" : "Confirm selected portion"}</button></section>}
    <section className="assessment-editor-panel"><div className="section-title"><div><span className="section-kicker">Blueprint → teacher draft</span><h2>Question paper</h2><p>{inReview ? "This submitted version is frozen while an authorised academic reviewer checks it." : "Question IDs remain stable while you edit and reorder. Marking guides stay attached to each question."}</p></div><div className="assessment-editor-actions"><button className="button" onClick={addQuestion} disabled={teacherLocked}><Plus size={15} />Add question</button><button className="button" onClick={generateAI} disabled={aiBusy || teacherLocked}><Sparkles size={15} />{aiBusy ? "Preparing…" : "Draft with ATE"}</button><button className="button button-primary" onClick={save} disabled={busy || teacherLocked}><Save size={15} />{busy ? "Saving…" : "Save version"}</button></div></div>
      <div className="assessment-quality-panel"><div><span>Marks</span><strong className={questionMarks === Number(data.workspace.total_marks) ? "good" : "warn"}>{questionMarks} / {text(data.workspace.total_marks)}</strong></div><div><span>Eligible scope</span><strong>{data.scopeItems.filter((item) => ["CONFIRMED_ELIGIBLE", "BROADER_PROFILE_PERMITTED"].includes(text(item.scope_state))).length}</strong></div><div><span>Out-of-scope items</span><strong className={outOfScope ? "warn" : "good"}>{outOfScope}</strong></div><div><span>Marking guides</span><strong>{payload.questions.filter((question) => question.markingGuide.some(Boolean)).length} / {payload.questions.length}</strong></div><div><span>Blueprint</span><strong className="good">Present</strong></div></div>
      {errors.length > 0 && <div className="assessment-warning" role="status">{errors[0]}</div>}
      {proposal && <div className="assessment-ai-proposal"><div><span className="section-kicker">AI proposal · teacher review required</span><h3>{proposal.content.title}</h3><p>Generated inside the approved blueprint. No version exists until you accept this exact fingerprinted proposal.</p></div><div className="ai-proposal-summary"><span>{proposal.content.questions.length} questions</span><span>{proposal.content.totalMarks} marks</span><span>Fingerprint {proposal.outputFingerprint.slice(0, 12)}…</span></div><div className="ai-proposal-preview">{proposal.content.questions.map((question, index) => <div key={question.id}><strong>{index + 1}. {question.text}</strong><small>{question.marks} marks · {question.itemType} · {question.canonicalIds.join(", ")}</small></div>)}</div><div className="assessment-editor-actions"><button className="button" onClick={rejectAI} disabled={aiBusy}>Reject proposal</button><button className="button button-primary" onClick={acceptAI} disabled={aiBusy}><Check size={15} />Accept exact proposal</button></div></div>}
      <div className="question-list">{payload.questions.length === 0 ? <div className="assessment-empty"><ClipboardCheck size={17} /><div><strong>No questions yet.</strong><p>Start manually; AI drafting is optional and remains a teacher-reviewed proposal.</p></div></div> : payload.questions.map((question, index) => <article className="question-editor" key={question.id}><div className="question-number">{index + 1}</div><div className="question-editor-main"><div className="question-editor-top"><label className="question-text-field">Question text<textarea rows={3} value={question.text} onChange={(event) => updateQuestion(index, { text: event.target.value })} disabled={teacherLocked} placeholder="Write the question or task…" /></label><div className="question-side-fields"><label>Marks<input type="number" min="1" value={question.marks} onChange={(event) => updateQuestion(index, { marks: Number(event.target.value) })} disabled={teacherLocked} /></label><label>Item type<select value={question.itemType} onChange={(event) => updateQuestion(index, { itemType: event.target.value as typeof question.itemType })} disabled={teacherLocked}>{assessmentItemTypes.map((item) => <option key={item}>{item}</option>)}</select></label><label>Difficulty<select value={question.difficulty} onChange={(event) => updateQuestion(index, { difficulty: event.target.value as typeof question.difficulty })} disabled={teacherLocked}>{assessmentDifficulties.map((item) => <option key={item}>{item}</option>)}</select></label></div></div><label>Eligible curriculum IDs<input value={question.canonicalIds.join(", ")} onChange={(event) => updateQuestion(index, { canonicalIds: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} disabled={teacherLocked} /></label><label>Marking guide<textarea rows={2} value={question.markingGuide.join("\n")} onChange={(event) => updateQuestion(index, { markingGuide: event.target.value.split("\n") })} disabled={teacherLocked} /></label></div><div className="question-editor-tools"><button className="icon-button" title="Move up" onClick={() => move(index, -1)} disabled={teacherLocked || index === 0}><ArrowUp size={15} /></button><button className="icon-button" title="Move down" onClick={() => move(index, 1)} disabled={teacherLocked || index === payload.questions.length - 1}><ArrowDown size={15} /></button><button className="icon-button danger" title="Delete question" onClick={() => setPayload((current) => ({ ...current, questions: current.questions.filter((_, itemIndex) => itemIndex !== index) }))} disabled={teacherLocked}><Trash2 size={15} /></button></div></article>)}</div>
      {message && <p className={message.startsWith("Saved") || message.startsWith("Assessment finalised") || message.startsWith("Assessment submitted") ? "form-success" : "form-error"} role="status">{message}</p>}
    </section>
    <section className="assessment-finalise-panel"><div><span className="section-kicker">Deterministic review gate</span><h2>{inReview ? "Awaiting academic review" : requiresReview ? "Submit for academic review" : "Ready for finalisation?"}</h2><p>{inReview ? "An authorised HOD or DOS is reviewing this submitted version. Your editing controls are frozen until a decision is recorded." : requiresReview ? "This assessment profile requires an authorised academic review before the assessment can become final." : "Finalisation freezes this version, stores the scope snapshot and records the actor/time. Editing later requires a new draft revision."}</p>{final && <div className="assessment-export-links"><a className="button" href={`/api/teacher/assessments/${text(data.workspace.id)}/pdf?kind=question-paper`}>Question Paper PDF</a><a className="button" href={`/api/teacher/assessments/${text(data.workspace.id)}/docx?kind=question-paper`}>Question Paper DOCX</a><a className="button" href={`/api/teacher/assessments/${text(data.workspace.id)}/pdf?kind=marking-guide`}>Marking Guide PDF</a><a className="button" href={`/api/teacher/assessments/${text(data.workspace.id)}/docx?kind=marking-guide`}>Marking Guide DOCX</a></div>}</div>{requiresReview ? <button className="button button-primary" onClick={submitForReview} disabled={busy || teacherLocked || questionMarks !== Number(data.workspace.total_marks) || outOfScope > 0}><ClipboardCheck size={15} />{inReview ? "Under academic review" : "Submit for review"}</button> : <button className="button button-primary" onClick={finalize} disabled={busy || final || questionMarks !== Number(data.workspace.total_marks) || outOfScope > 0}><LockKeyhole size={15} />{final ? "Final version locked" : "Finalise assessment"}</button>}</section>
  </main>;
}
