"use client";

import Link from "next/link";
import { ArrowLeft, ArrowUpRight, BookOpen, Check, History, MapPin, RotateCcw } from "lucide-react";
import { useState, useTransition } from "react";
import type { TeachingSectionData } from "@/teacher/application/queries";
import { confirmTeacherCurriculumPosition } from "@/teacher/application/ui-actions";

function formatTime(value: string, timeZone: string) { return new Intl.DateTimeFormat("en-UG", { weekday: "short", day: "numeric", month: "short", hour: "numeric", minute: "2-digit", timeZone }).format(new Date(value)); }
function statusLabel(outcome: string | null) { return outcome === "DELIVERED" ? "Delivered" : outcome === "PARTIALLY_DELIVERED" ? "Partially delivered" : outcome === "NOT_DELIVERED" ? "Not delivered" : outcome === "CHANGED" ? "Changed from plan" : "Awaiting record"; }

export function TeachingSectionWorkspace({ data }: { data: TeachingSectionData }) {
  const { section, curriculum } = data;
  const [editingPosition, setEditingPosition] = useState(!curriculum.current);
  const [selectedId, setSelectedId] = useState(curriculum.current?.canonicalId ?? curriculum.options[0]?.canonicalId ?? "");
  const [reason, setReason] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const selected = curriculum.options.find((option) => option.canonicalId === selectedId);
  const submitPosition = () => startTransition(async () => {
    const result = await confirmTeacherCurriculumPosition({ teachingSectionId: section.id, canonicalId: selectedId, positionKind: selected?.positionKind ?? "TOPIC", correctionReason: curriculum.current ? reason : undefined });
    setMessage(result.ok ? curriculum.current ? "Confirmed correction. The previous position remains in history." : "Starting position confirmed for this Teaching Section." : result.error);
    if (result.ok) { setEditingPosition(false); setReason(""); }
  });
  return <div className="teacher-page section-workspace">
    <Link className="back-link" href="/workspace"><ArrowLeft size={15} />Teacher Home</Link>
    <header className="teacher-heading section-heading"><div><p className="eyebrow">Teaching Section</p><h1>{section.subjectName}</h1><p className="lede">{section.classLevelName} · {section.streamName} · {section.academicPeriodName}</p></div><div className="section-identity"><BookOpen size={17} /><span><strong>{data.schoolName}</strong><small>Assigned teacher · {data.access.displayName}</small></span></div></header>
    {message && <div className={`teacher-message ${message.startsWith("Confirmed") || message.startsWith("Starting") ? "success" : "error"}`} role="status">{message.startsWith("Confirmed") || message.startsWith("Starting") ? <Check size={16} /> : <RotateCcw size={16} />}{message}</div>}
    <section className="section-overview"><div className="section-overview-main"><span className="section-kicker">Current confirmed position</span>{curriculum.current ? <><h2>{curriculum.current.title}</h2><p>{curriculum.current.positionKind === "TOPIC" ? "Topic" : "Learning outcome"} · {curriculum.current.sourceWording}</p><span className="provenance"><i />Governed curriculum context · {curriculum.current.sourceTitle}</span></> : <div className="section-empty"><MapPin size={18} /><div><strong>No position has been confirmed yet.</strong><p>Choose the valid governed starting point for this class before preparing its next lesson.</p></div></div>}</div><div className="section-overview-action"><span className="status status-info">{curriculum.profileTitle}</span>{curriculum.current && !editingPosition && <button className="button" onClick={() => { setSelectedId(curriculum.current?.canonicalId ?? ""); setEditingPosition(true); }}>Correct position</button>}</div></section>
    {editingPosition && <section className="position-editor" aria-labelledby="position-editor-title"><div><span className="section-kicker">{curriculum.current ? "Append a correction" : "First-position setup"}</span><h2 id="position-editor-title">Which governed position is this class at?</h2><p>ATE will append a new teacher-confirmed event. It will not rewrite the previous position.</p></div><label>Curriculum position<select value={selectedId} onChange={(event) => setSelectedId(event.target.value)}>{curriculum.options.map((option) => <option key={option.canonicalId} value={option.canonicalId}>{option.positionKind === "TOPIC" ? "Topic" : "Learning outcome"} · {option.title}</option>)}</select></label>{curriculum.current && <label>Why is this a correction?<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={2} placeholder="For example: confirmed after reviewing the previous lesson record." required /></label>}<div className="action-row"><button className="button button-primary" disabled={pending || !selectedId || (Boolean(curriculum.current) && !reason.trim())} onClick={submitPosition}>{pending ? "Saving…" : curriculum.current ? "Save correction" : "Confirm starting position"}</button>{curriculum.current && <button className="button button-quiet" onClick={() => setEditingPosition(false)}>Cancel</button>}</div></section>}
    <div className="section-columns"><section className="section-panel"><div className="section-title"><div><span className="section-kicker">Next lesson</span><h2>Prepare from this class context</h2></div></div>{data.nextLesson ? <div className="section-next-lesson"><div><strong>{formatTime(data.nextLesson.startsAt, data.schoolTimezone)}</strong><span>{data.nextLesson.roomLabel ? `Room ${data.nextLesson.roomLabel}` : "Scheduled timetable occurrence"}</span></div><Link className="button button-primary" href={`/workspace/teacher/lessons/${data.nextLesson.id}`}>Open readiness <ArrowUpRight size={15} /></Link></div> : <div className="teacher-empty compact"><BookOpen size={17} /><span>No future lesson is scheduled for this Teaching Section.</span></div>}</section><section className="section-panel"><div className="section-title"><div><span className="section-kicker">Recent classroom continuity</span><h2>What actually happened</h2></div></div>{data.recentLessons.length ? <div className="continuity-mini-list">{data.recentLessons.map((lesson) => <div className="continuity-mini-row" key={lesson.id}><span><strong>{formatTime(lesson.startsAt, data.schoolTimezone)}</strong><small>{lesson.unfinishedWork || lesson.eventNote || "No unfinished note recorded."}</small></span><span className={`status ${lesson.outcome === "DELIVERED" ? "status-positive" : lesson.outcome ? "status-attention" : "status-neutral"}`}>{statusLabel(lesson.outcome)}</span></div>)}</div> : <div className="teacher-empty compact"><History size={17} /><span>No classroom evidence has been recorded yet.</span></div>}</section></div>
    <section className="position-history"><div className="section-title"><div><span className="section-kicker">Append-only history</span><h2>Curriculum position history</h2><p>Corrections preserve the original event and its reason.</p></div></div>{data.positionHistory.length ? <div className="history-list">{data.positionHistory.map((item) => <div className="history-row" key={item.eventId}><span className="history-mark" /><span><strong>{item.title}</strong><small>{item.positionKind === "LEARNING_OUTCOME" ? "Learning outcome" : "Topic"} · {new Intl.DateTimeFormat("en-UG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.confirmedAt))}</small>{item.correctionReason && <em>Correction: {item.correctionReason}</em>}</span></div>)}</div> : <div className="teacher-empty compact"><History size={17} /><span>No position events yet. Use the controlled setup above.</span></div>}</section>
  </div>;
}
