import Link from "next/link";
import { ArrowUpRight, BookOpen, CalendarDays, CircleAlert, Clock3 } from "lucide-react";
import type { TeacherHomeData, TeacherLesson } from "@/teacher/application/queries";

function formatTime(value: string, timeZone: string) { return new Intl.DateTimeFormat("en-UG", { hour: "numeric", minute: "2-digit", timeZone }).format(new Date(value)); }
function formatDate(value: string, timeZone: string) { return new Intl.DateTimeFormat("en-UG", { weekday: "long", day: "numeric", month: "long", timeZone }).format(new Date(value)); }
function lessonStatus(lesson: TeacherLesson) { if (lesson.eventId) return { label: lesson.outcome === "PARTIALLY_DELIVERED" ? "Partially delivered" : lesson.outcome === "NOT_DELIVERED" ? "Not delivered" : lesson.outcome === "CHANGED" ? "Changed from plan" : "Recorded", tone: lesson.outcome === "DELIVERED" ? "positive" : "attention" }; if (new Date(lesson.endsAt) < new Date()) return { label: "Needs record", tone: "attention" }; return { label: new Date(lesson.startsAt) <= new Date() ? "In progress" : "Upcoming", tone: "neutral" }; }
function previousStateLabel(lesson: TeacherLesson) { if (lesson.carryForwardState === "PARTIAL_CARRY_FORWARD") return "Previous lesson was partially delivered"; if (lesson.carryForwardState === "NOT_DELIVERED_CARRY_FORWARD") return "Previous scheduled lesson was not delivered"; if (lesson.carryForwardState === "CHANGED_REVIEW") return "Previous lesson changed from plan"; return "No previous delivery record"; }

export function TeacherHome({ data }: { data: TeacherHomeData }) {
  const next = data.nextLesson;
  const firstName = data.access.displayName.trim().split(/\s+/)[0] || "teacher";
  const hour = Number(new Intl.DateTimeFormat("en-GB", { hour: "numeric", hourCycle: "h23", timeZone: data.schoolTimezone }).format(new Date()));
  const greeting = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";
  const unconfirmed = data.attention.filter((item) => item.kind === "UNCONFIRMED");
  const otherAttention = data.attention.filter((item) => item.kind !== "UNCONFIRMED");
  return <div className="teacher-page">
    <header className="teacher-heading"><div><p className="eyebrow">Teacher home</p><h1>{greeting}, {firstName}.</h1><p className="lede">{formatDate(new Date().toISOString(), data.schoolTimezone)} · {data.schoolName}</p></div></header>
    {data.continuityWarning && <div className="teacher-message warning" role="status"><CircleAlert size={16} />{data.continuityWarning}</div>}
    <section className="next-lesson" aria-labelledby="next-lesson-title">{next ? <><div className="next-lesson-main"><div className="next-lesson-label"><span className="section-kicker">Next lesson</span><span className="next-lesson-date">{formatDate(next.startsAt, data.schoolTimezone)}</span></div><h2 id="next-lesson-title">{next.section.subjectName} · {next.section.classLevelName} {next.section.streamName}</h2><div className="next-lesson-time"><Clock3 size={18} /><strong>{formatTime(next.startsAt, data.schoolTimezone)}–{formatTime(next.endsAt, data.schoolTimezone)}</strong>{next.roomLabel && <span>{next.roomLabel}</span>}</div><div className="next-context-grid"><div><span>Topic</span><strong>{next.currentPosition?.title || "Choose the current topic"}</strong>{next.unfinishedWork && <p>Carry forward: {next.unfinishedWork}</p>}</div><div><span>Last lesson</span><strong>{previousStateLabel(next)}</strong></div></div></div><div className="next-lesson-action"><Link className="button button-primary" href={`/workspace/teacher/lessons/${next.id}`}><BookOpen size={17} />Prepare lesson <ArrowUpRight size={16} /></Link></div></> : <div className="teacher-empty"><BookOpen size={19} /><div><h2 id="next-lesson-title">No upcoming lesson is scheduled.</h2><p>Your lessons will appear here when the school timetable is active.</p></div></div>}</section>
    {unconfirmed.length > 0 && <Link className="teacher-attention-summary" href="/workspace/classroom"><CircleAlert size={20} /><span><strong>{unconfirmed.length} past {unconfirmed.length === 1 ? "lesson needs" : "lessons need"} a classroom record</strong><small>Confirm what happened when you are ready.</small></span><span className="teacher-attention-review">Review <ArrowUpRight size={16} /></span></Link>}
    {otherAttention.length > 0 && <section className="teacher-attention" aria-labelledby="teacher-attention-title"><div className="attention-heading"><CircleAlert size={17} /><div><h2 id="teacher-attention-title">Needs your attention</h2></div></div><div className="teacher-attention-list">{otherAttention.map((item) => <Link className="teacher-attention-item" href={item.lessonId ? `/workspace/teacher/lessons/${item.lessonId}` : "/workspace/teacher/sections"} key={item.id}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowUpRight size={16} /></Link>)}</div></section>}
    <section className="teacher-today" aria-labelledby="today-title"><div className="section-title"><div><h2 id="today-title">Today</h2></div><Link className="quiet-link" href="/workspace/teacher/sections">Your classes <ArrowUpRight size={15} /></Link></div>{data.todayLessons.length === 0 ? <div className="teacher-empty compact"><CalendarDays size={18} /><div><strong>No lessons scheduled today.</strong><p>Check your classes for upcoming lessons.</p></div></div> : <div className="teacher-schedule">{data.todayLessons.map((lesson) => { const status = lessonStatus(lesson); return <Link className="schedule-row" href={`/workspace/teacher/lessons/${lesson.id}`} key={lesson.id}><span className="schedule-time">{formatTime(lesson.startsAt, data.schoolTimezone)}<small>{formatTime(lesson.endsAt, data.schoolTimezone)}</small></span><span className="schedule-detail"><strong>{lesson.section.subjectName} · {lesson.section.classLevelName} {lesson.section.streamName}</strong><small>{lesson.currentPosition?.title || "Topic not selected"}</small></span><span className={`status status-${status.tone}`}>{status.label}</span><ArrowUpRight size={16} /></Link>; })}</div>}</section>
  </div>;
}
