import Link from "next/link";
import { ArrowUpRight, BookOpen, CalendarDays, Check, CircleAlert, Clock3 } from "lucide-react";
import type { TeacherHomeData, TeacherLesson } from "@/teacher/application/queries";

function formatTime(value: string, timeZone: string) { return new Intl.DateTimeFormat("en-UG", { hour: "numeric", minute: "2-digit", timeZone }).format(new Date(value)); }
function formatDate(value: string, timeZone: string) { return new Intl.DateTimeFormat("en-UG", { weekday: "long", day: "numeric", month: "long", timeZone }).format(new Date(value)); }
function lessonStatus(lesson: TeacherLesson) { if (lesson.eventId) return { label: lesson.outcome === "PARTIALLY_DELIVERED" ? "Partially delivered" : lesson.outcome === "NOT_DELIVERED" ? "Not delivered" : lesson.outcome === "CHANGED" ? "Changed from plan" : "Recorded", tone: lesson.outcome === "DELIVERED" ? "positive" : "attention" }; if (new Date(lesson.endsAt) < new Date()) return { label: "Needs record", tone: "attention" }; return { label: new Date(lesson.startsAt) <= new Date() ? "In progress" : "Upcoming", tone: "neutral" }; }
function previousStateLabel(lesson: TeacherLesson) { if (lesson.carryForwardState === "PARTIAL_CARRY_FORWARD") return "Previous lesson was partially delivered"; if (lesson.carryForwardState === "NOT_DELIVERED_CARRY_FORWARD") return "Previous scheduled lesson was not delivered"; if (lesson.carryForwardState === "CHANGED_REVIEW") return "Previous lesson changed from plan"; return "No previous delivery record"; }

export function TeacherHome({ data }: { data: TeacherHomeData }) {
  const next = data.nextLesson;
  return <div className="teacher-page">
    <header className="teacher-heading"><div><p className="eyebrow">Teacher Home</p><h1>Your teaching day.</h1><p className="lede">{formatDate(new Date().toISOString(), data.schoolTimezone)} · {data.schoolName}</p></div><div className="teacher-heading-note"><Clock3 size={16} /><span>Classroom reality is always teacher-confirmed.</span></div></header>
    {data.attention.length > 0 && <section className="teacher-attention" aria-labelledby="teacher-attention-title"><div className="attention-heading"><CircleAlert size={17} /><div><h2 id="teacher-attention-title">Needs your attention</h2><p>Only exceptions that affect your next academic action appear here.</p></div></div><div className="teacher-attention-list">{data.attention.map((item) => <Link className="teacher-attention-item" href={item.lessonId ? `/workspace/teacher/lessons/${item.lessonId}` : "/workspace/teacher/sections"} key={item.id}><span><strong>{item.title}</strong><small>{item.detail}</small></span><ArrowUpRight size={16} /></Link>)}</div></section>}
    {data.continuityWarning && <div className="teacher-message warning" role="status"><CircleAlert size={16} />{data.continuityWarning}</div>}
    <section className="next-lesson" aria-labelledby="next-lesson-title">{next ? <><div className="next-lesson-main"><div className="next-lesson-label"><span className="section-kicker">Next lesson</span><span className="next-lesson-date">{formatDate(next.startsAt, data.schoolTimezone)}</span></div><h2 id="next-lesson-title">{next.section.subjectName}</h2><p className="lesson-identity">{next.section.classLevelName} · {next.section.streamName} · {next.section.academicPeriodName}</p><div className="next-lesson-time"><Clock3 size={18} /><strong>{formatTime(next.startsAt, data.schoolTimezone)}–{formatTime(next.endsAt, data.schoolTimezone)}</strong>{next.roomLabel && <span>Room {next.roomLabel}</span>}</div><div className="next-context-grid"><div><span>Where this class stopped</span><strong>{next.currentPosition?.title || "No teaching position confirmed"}</strong><p>{next.unfinishedWork || "No unfinished work carried forward."}</p></div><div><span>Previous classroom state</span><strong>{previousStateLabel(next)}</strong><p>{next.unfinishedWork || "Open readiness to see this class's current topic and outcome."}</p></div></div></div><div className="next-lesson-action"><span className="status status-info">{next.preparation ? "Preparation saved" : "Preparation needed"}</span><Link className="button button-primary" href={`/workspace/teacher/lessons/${next.id}`}>Prepare lesson <ArrowUpRight size={16} /></Link><Link className="quiet-link" href={`/workspace/teacher/sections/${next.section.id}`}>Open Teaching Section</Link></div></> : <div className="teacher-empty"><BookOpen size={19} /><div><h2 id="next-lesson-title">No upcoming lesson is scheduled.</h2><p>Your confirmed timetable lessons will appear here once the school schedule is active.</p></div></div>}</section>
    <section className="teacher-today" aria-labelledby="today-title"><div className="section-title"><div><span className="section-kicker">Today</span><h2 id="today-title">Your schedule</h2><p>Scheduled lessons are timetable intent. A recorded outcome is separate classroom evidence.</p></div><Link className="quiet-link" href="/workspace/classroom">View classroom records</Link></div>{data.todayLessons.length === 0 ? <div className="teacher-empty compact"><CalendarDays size={18} /><div><strong>No lessons scheduled today.</strong><p>There is no active timetable occurrence for your Teaching Sections today.</p></div></div> : <div className="teacher-schedule">{data.todayLessons.map((lesson) => { const status = lessonStatus(lesson); return <Link className="schedule-row" href={`/workspace/teacher/lessons/${lesson.id}`} key={lesson.id}><span className="schedule-time">{formatTime(lesson.startsAt, data.schoolTimezone)}<small>{formatTime(lesson.endsAt, data.schoolTimezone)}</small></span><span className="schedule-detail"><strong>{lesson.section.subjectName}</strong><small>{lesson.section.classLevelName} · {lesson.section.streamName}</small></span><span className={`status status-${status.tone}`}>{status.label}</span><ArrowUpRight size={16} /></Link>; })}</div>}</section>
    <section className="teacher-footer-note"><Check size={17} /><span>Next steps are based on verified curriculum context and teacher-confirmed classroom evidence.</span></section>
  </div>;
}
