"use client";

import { Check, CircleAlert, FilePlus2, ShieldCheck, Sparkles } from "lucide-react";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { joinLines, parseLessonPayload, recommendTeachingPack } from "@/artifacts/lesson";
import { createTeachingPackArtifact, saveLessonArtifactVersion } from "@/teacher/application/artifact-actions";
import { acceptAIProposal, askATEForArtifact, generateTeachingPackDraft, rejectAIProposal, type AIProposal } from "@/teacher/application/ai-artifact-actions";
import { AIProposalError, AIProposalHint, AIProposalPanel } from "./AIProposalPanel";
import type { LessonArtifactRecord, LessonReadinessData } from "@/teacher/application/queries";
import type { ActivitySheetPayload, BoardNotesPayload, HomeworkPayload, LearnerNotesPayload, LessonSummaryPayload } from "@/artifacts/types";

type PackPayload = BoardNotesPayload | LearnerNotesPayload | ActivitySheetPayload | LessonSummaryPayload | HomeworkPayload;
const labels: Record<string, string> = { BOARD_NOTES: "Board Notes", LEARNER_NOTES: "Learner Notes", ACTIVITY_SHEET: "Activity Sheet", LESSON_SUMMARY: "Lesson Summary", HOMEWORK: "Homework" };
const descriptions: Record<string, string> = { BOARD_NOTES: "Concise concepts, equations, examples or board points", LEARNER_NOTES: "A retained written reference when learners need one", ACTIVITY_SHEET: "Learner activity / worksheet based on the lesson structure", LESSON_SUMMARY: "A concise recap to carry the lesson forward", HOMEWORK: "Follow-up tasks connected to this lesson" };

export function TeachingPackWorkspace({ data }: { data: LessonReadinessData }) {
  const plan = data.artifacts.find((item) => item.artifactType === "FORMAL_LESSON_PLAN");
  const parsedPlan = plan?.currentContent ? parseLessonPayload("FORMAL_LESSON_PLAN", plan.currentContent) : null;
  const recommendations = parsedPlan ? recommendTeachingPack(parsedPlan) : [];
  const children = data.artifacts.filter((item) => item.artifactType !== "FORMAL_LESSON_PLAN");
  const [message, setMessage] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const [aiProposal, setAiProposal] = useState<AIProposal | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);
  const router = useRouter();
  const create = (artifactType: Exclude<LessonArtifactRecord["artifactType"], "FORMAL_LESSON_PLAN">) => startTransition(async () => { const result = await createTeachingPackArtifact({ scheduledLessonId: data.lesson.id, artifactType }); setMessage(result.ok ? `${labels[artifactType]} created as version ${result.version}.` : result.error); if (result.ok) router.refresh(); });
  const generate = (artifactType: Exclude<LessonArtifactRecord["artifactType"], "FORMAL_LESSON_PLAN">) => startTransition(async () => { setAiError(null); const result = await generateTeachingPackDraft({ scheduledLessonId: data.lesson.id, artifactType }); setAiProposal(result); if (!result.ok) setAiError(result.error); });
  const accept = () => { if (!aiProposal?.ok) return; startTransition(async () => { const result = await acceptAIProposal({ runId: aiProposal.runId, scheduledLessonId: data.lesson.id, artifactId: aiProposal.artifactId, artifactType: aiProposal.artifactType, expectedVersion: aiProposal.expectedVersion, parentArtifactId: aiProposal.parentArtifactId, parentVersionId: aiProposal.parentVersionId, content: aiProposal.content, contextFingerprint: aiProposal.contextFingerprint, outputFingerprint: aiProposal.outputFingerprint, instruction: aiProposal.instruction, selectedField: aiProposal.selectedField, changeSummary: "Teacher accepted ATE Teaching Pack proposal" }); setMessage(result.ok ? `ATE proposal saved as version ${result.version}.` : result.error); if (result.ok) { setAiProposal(null); router.refresh(); } }); };
  const reject = () => { if (!aiProposal?.ok) return; startTransition(async () => { const result = await rejectAIProposal(aiProposal.runId); setAiProposal(null); setMessage(result.ok ? "ATE proposal rejected; no artifact version was created." : result.error || "Proposal could not be rejected."); }); };
  return <div className="pack-workspace">
    <div className="pack-heading"><div><span className="section-kicker">Lesson-specific child artifacts</span><h2>Teaching Pack</h2><p>Materials derive from the saved Formal Lesson Plan version. Create only what helps this lesson.</p></div><span className="status status-info"><ShieldCheck size={13} />Teacher remains final authority</span></div>
    {data.lesson.unfinishedWork && <div className="carry-forward-box pack-carry-forward"><strong>Carry forward from the previous lesson</strong><span>{data.lesson.unfinishedWork}</span></div>}
    {message && <div className={`teacher-message ${message.includes("could not") ? "error" : "success"}`} role="status">{message.includes("could not") ? <CircleAlert size={16} /> : <Check size={16} />}{message}</div>}
    {aiError && <AIProposalError message={aiError} />}
    {aiProposal?.ok && <AIProposalPanel proposal={aiProposal} pending={pending} onAccept={accept} onReject={reject} />}
    {!plan?.currentVersionId ? <div className="artifact-empty"><FilePlus2 size={18} /><div><strong>Save the Formal Lesson Plan first.</strong><p>Teaching Pack materials must retain the exact parent plan version they were prepared from.</p></div></div> : <><section className="pack-recommendations"><div className="section-title"><div><span className="section-kicker">Deterministic recommendations</span><h3>Recommended for this lesson</h3><p>Rules identify useful material types; ATE generation remains optional and teacher-reviewed.</p></div></div>{recommendations.length === 0 ? <div className="pack-optional-note">No strong signal was found. Materials are optional for this lesson.</div> : <div className="pack-recommendation-list">{recommendations.map((recommendation) => <PackCreateCard key={recommendation.artifactType} title={recommendation.title} reason={recommendation.reason} created={children.some((item) => item.artifactType === recommendation.artifactType)} pending={pending} onCreate={() => create(recommendation.artifactType)} onGenerate={() => generate(recommendation.artifactType)} />)}</div>}</section><section className="pack-optional"><div className="section-title"><div><span className="section-kicker">Optional materials</span><h3>Add only what is useful</h3></div></div><div className="pack-recommendation-list">{(["BOARD_NOTES", "ACTIVITY_SHEET", "LEARNER_NOTES", "LESSON_SUMMARY", "HOMEWORK"] as const).map((type) => <PackCreateCard key={type} title={labels[type]} reason={descriptions[type]} created={children.some((item) => item.artifactType === type)} pending={pending} onCreate={() => create(type)} onGenerate={() => generate(type)} />)}</div></section>{children.map((artifact) => <PackArtifactEditor artifact={artifact} lessonId={data.lesson.id} pending={pending} setMessage={setMessage} key={artifact.id} />)}</>}
  </div>;
}

function PackCreateCard({ title, reason, created, pending, onCreate, onGenerate }: { title: string; reason: string; created: boolean; pending: boolean; onCreate: () => void; onGenerate: () => void }) { return <div className="pack-create-card"><div><strong>{title}</strong><p>{reason}</p></div>{created ? <span className="saved-state"><Check size={14} />Created</span> : <div className="action-row"><button className="button small" type="button" onClick={onCreate} disabled={pending}><FilePlus2 size={14} />Create</button><button className="button small button-quiet" type="button" onClick={onGenerate} disabled={pending}><Sparkles size={14} />Generate</button></div>}</div>; }

function PackArtifactEditor({ artifact, lessonId, pending, setMessage }: { artifact: LessonArtifactRecord; lessonId: string; pending: boolean; setMessage: (message: string) => void }) {
  const router = useRouter();
  const [saving, startTransition] = useTransition();
  const [aiProposal, setAiProposal] = useState<AIProposal | null>(null);
  const [aiError, setAiError] = useState<string | null>(null);
  const [askInstruction, setAskInstruction] = useState("");
  const [content, setContent] = useState<PackPayload>(() => parseLessonPayload(artifact.artifactType as Exclude<LessonArtifactRecord["artifactType"], "FORMAL_LESSON_PLAN">, artifact.currentContent));
  const [kept, setKept] = useState(false);
  const save = () => startTransition(async () => { const result = await saveLessonArtifactVersion({ scheduledLessonId: lessonId, artifactType: artifact.artifactType, content, expectedVersion: artifact.currentVersionNumber }); setMessage(result.ok ? `${labels[artifact.artifactType]} saved as version ${result.version}.` : result.error); if (result.ok) router.refresh(); });
  const generate = () => startTransition(async () => { setAiError(null); const result = await generateTeachingPackDraft({ scheduledLessonId: lessonId, artifactType: artifact.artifactType as Exclude<LessonArtifactRecord["artifactType"], "FORMAL_LESSON_PLAN"> }); setAiProposal(result); if (!result.ok) setAiError(result.error); });
  const ask = () => startTransition(async () => { if (!askInstruction.trim()) return; setAiError(null); const result = await askATEForArtifact({ scheduledLessonId: lessonId, artifactId: artifact.id, artifactType: artifact.artifactType, instruction: askInstruction }); setAiProposal(result); if (!result.ok) setAiError(result.error); });
  const accept = () => { if (!aiProposal?.ok) return; startTransition(async () => { const result = await acceptAIProposal({ runId: aiProposal.runId, scheduledLessonId: lessonId, artifactId: aiProposal.artifactId, artifactType: aiProposal.artifactType, expectedVersion: aiProposal.expectedVersion, parentArtifactId: aiProposal.parentArtifactId, parentVersionId: aiProposal.parentVersionId, content: aiProposal.content, contextFingerprint: aiProposal.contextFingerprint, changeSummary: "Teacher accepted ATE Teaching Pack proposal" }); setMessage(result.ok ? `${labels[artifact.artifactType]} saved as version ${result.version}.` : result.error); if (result.ok) { setAiProposal(null); router.refresh(); } }); };
  const reject = () => { if (!aiProposal?.ok) return; startTransition(async () => { const result = await rejectAIProposal(aiProposal.runId); setAiProposal(null); setMessage(result.ok ? "ATE proposal rejected; no artifact version was created." : result.error || "Proposal could not be rejected."); }); };
  const update = (value: Partial<PackPayload>) => setContent((current) => ({ ...current, ...value }) as PackPayload);
  const lines = (value: string) => value.split(/\r?\n/);
  return <section className="pack-editor" aria-labelledby={`pack-${artifact.id}`}><div className="artifact-editor-heading"><div><span className="section-kicker">{artifact.currentVersionNumber ? `Version ${artifact.currentVersionNumber}` : "Draft"}</span><h3 id={`pack-${artifact.id}`}>{labels[artifact.artifactType]}</h3><p>Derived from Formal Lesson Plan version {artifact.parentVersionId ? artifact.parentVersionId.slice(0, 8) : "—"}.</p></div><div className="pack-editor-actions"><button className="button small" type="button" onClick={generate} disabled={pending || saving}><Sparkles size={14} />Generate with ATE</button>{artifact.potentiallyStale && !kept && <span className="status status-warning">Potentially stale</span>}<span className="saved-state"><Check size={14} />Saved</span></div></div>{aiError && <AIProposalError message={aiError} />}{aiProposal?.ok && <AIProposalPanel proposal={aiProposal} pending={pending || saving} onAccept={accept} onReject={reject} />}{artifact.potentiallyStale && !kept && <div className="stale-note"><CircleAlert size={16} /><div><strong>{labels[artifact.artifactType]} may need review.</strong><span>The Formal Lesson Plan changed after this material was prepared.</span><div className="action-row"><button className="button small" type="button" onClick={() => setKept(true)}>Keep current version</button><button className="button small button-quiet" type="button" onClick={() => document.getElementById(`pack-${artifact.id}`)?.scrollIntoView({ behavior: "smooth", block: "start" })}>Review</button></div></div></div>}
    <PackFields artifactType={artifact.artifactType} content={content} update={update} lines={lines} /><div className="ask-ate-strip"><div><span className="section-kicker">Contextual Ask ATE</span><strong>Change only this material</strong><AIProposalHint /></div><div className="ask-ate-controls"><input value={askInstruction} onChange={(event) => setAskInstruction(event.target.value)} placeholder="Reduce this activity to 20 minutes…" maxLength={1000} /><button className="button small" type="button" onClick={ask} disabled={pending || saving || !askInstruction.trim()}><Sparkles size={14} />Preview changes</button></div></div><div className="editor-footer"><span className="provenance"><i />AI proposals and teacher edits create immutable versions.</span><div className="action-row"><a className="button small button-quiet" href={`/workspace/teacher/lessons/${lessonId}/print?artifactId=${artifact.id}`} target="_blank" rel="noreferrer">Print view</a><a className="button small button-quiet" href={`/api/teacher/lessons/${lessonId}/artifacts/${artifact.id}/pdf`} target="_blank" rel="noreferrer">PDF</a><a className="button small button-quiet" href={`/api/teacher/lessons/${lessonId}/artifacts/${artifact.id}/docx`}>DOCX</a><button className="button button-primary" type="button" onClick={save} disabled={pending || saving}><Check size={15} />{pending || saving ? "Saving…" : `Save ${labels[artifact.artifactType]}`}</button></div></div></section>;
}

function PackFields({ artifactType, content, update, lines }: { artifactType: string; content: PackPayload; update: (value: Partial<PackPayload>) => void; lines: (value: string) => string[] }) {
  switch (artifactType) {
    case "BOARD_NOTES": return <div className="artifact-form-grid"><label>Key points<textarea rows={4} value={joinLines((content as BoardNotesPayload).keyPoints)} onChange={(event) => update({ keyPoints: lines(event.target.value) })} /></label><label>Examples<textarea rows={4} value={joinLines((content as BoardNotesPayload).examples)} onChange={(event) => update({ examples: lines(event.target.value) })} /></label><label>Equations<textarea rows={3} value={joinLines((content as BoardNotesPayload).equations)} onChange={(event) => update({ equations: lines(event.target.value) })} /></label><label>Prompts<textarea rows={3} value={joinLines((content as BoardNotesPayload).prompts)} onChange={(event) => update({ prompts: lines(event.target.value) })} /></label></div>;
    case "LEARNER_NOTES": return <div className="artifact-form-grid"><label>Key concepts<textarea rows={4} value={joinLines((content as LearnerNotesPayload).keyConcepts)} onChange={(event) => update({ keyConcepts: lines(event.target.value) })} /></label><label>Explanation<textarea rows={5} value={(content as LearnerNotesPayload).explanation} onChange={(event) => update({ explanation: event.target.value })} /></label><label>Examples<textarea rows={4} value={joinLines((content as LearnerNotesPayload).examples)} onChange={(event) => update({ examples: lines(event.target.value) })} /></label><label>Applications<textarea rows={4} value={joinLines((content as LearnerNotesPayload).applications)} onChange={(event) => update({ applications: lines(event.target.value) })} /></label><label>Summary<textarea rows={4} value={(content as LearnerNotesPayload).summary} onChange={(event) => update({ summary: event.target.value })} /></label></div>;
    case "ACTIVITY_SHEET": return <div className="artifact-form-grid"><label>Instructions<textarea rows={4} value={(content as ActivitySheetPayload).instructions} onChange={(event) => update({ instructions: event.target.value })} /></label><label>Materials required<textarea rows={3} value={joinLines((content as ActivitySheetPayload).materialsRequired)} onChange={(event) => update({ materialsRequired: lines(event.target.value) })} /></label><label>Tasks<textarea rows={5} value={joinLines((content as ActivitySheetPayload).tasks)} onChange={(event) => update({ tasks: lines(event.target.value) })} /></label><label>Questions<textarea rows={4} value={joinLines((content as ActivitySheetPayload).questions)} onChange={(event) => update({ questions: lines(event.target.value) })} /></label><label>Observation / response area<textarea rows={4} value={(content as ActivitySheetPayload).observationResponseArea} onChange={(event) => update({ observationResponseArea: event.target.value })} /></label><label>Conclusion prompts<textarea rows={3} value={joinLines((content as ActivitySheetPayload).conclusionPrompts)} onChange={(event) => update({ conclusionPrompts: lines(event.target.value) })} /></label></div>;
    case "LESSON_SUMMARY": return <div className="artifact-form-grid"><label>Key takeaways<textarea rows={4} value={joinLines((content as LessonSummaryPayload).keyTakeaways)} onChange={(event) => update({ keyTakeaways: lines(event.target.value) })} /></label><label>Concise summary<textarea rows={5} value={(content as LessonSummaryPayload).conciseSummary} onChange={(event) => update({ conciseSummary: event.target.value })} /></label><label>Learner reflection (optional)<textarea rows={4} value={(content as LessonSummaryPayload).learnerReflection} onChange={(event) => update({ learnerReflection: event.target.value })} /></label></div>;
    case "HOMEWORK": return <div className="artifact-form-grid"><label>Instructions<textarea rows={4} value={(content as HomeworkPayload).instructions} onChange={(event) => update({ instructions: event.target.value })} /></label><label>Tasks / questions<textarea rows={5} value={joinLines((content as HomeworkPayload).tasks)} onChange={(event) => update({ tasks: lines(event.target.value) })} /></label><label>Follow-up notes<textarea rows={4} value={(content as HomeworkPayload).followUpNotes} onChange={(event) => update({ followUpNotes: event.target.value })} /></label></div>;
    default: return null;
  }
}
